language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

gemfile:
  - Gemfile

bundler_args: ''

# for the rails 2.3 test app.
before_install:
  - ruby -e "exit(RUBY_VERSION == '2.0.0')" || gem update --system 1.8.25
  - gem --version

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bundle exec rake test:ci:install

script: "bundle exec rake test:ci"

# For all the integration tests
env:
  matrix:
    - RAILS_VERSION=2.3
    - RAILS_VERSION=3.0
    - RAILS_VERSION=3.1
    - RAILS_VERSION=3.2
    - UNITS=true

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: Gemfile
      env: RAILS_VERSION=2.3
    - rvm: 2.0.0
      gemfile: Gemfile
      env: RAILS_VERSION=3.0
    - rvm: 2.0.0
      gemfile: Gemfile
      env: RAILS_VERSION=3.1
