language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0

gemfile:
  - Gemfile-ci

bundler_args: ''

# for the rails 2.3 test app.
before_install:
  - ruby -e "exit(RUBY_VERSION == '2.0.0')" || gem update --system 1.8.25
  - gem --version

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bundle exec rake appraisal:gemfiles
  - bundle exec rake appraisal:install
  - bundle exec rake test:integration:selenium:install
  
script: "bundle exec rake test:ci"
